project:
  type: website

website:
  title: "Sequía en México"
  description: "Análisis territorial y temporal de la sequía en México (PRONACOSE)"
  navbar:
    background: primary
    pinned: true
    left:
      - href: index.qmd
        text: Inicio
      - href: mis_reportes/02-analisis_temporal.qmd
        text: Exploración
      - href: mis_reportes/04-conclusiones.qmd
        text: Resumen Ejecutivo
      - href: mis_reportes/05-dashboard.qmd
        text: Prueba

format:
  html:
    theme: darkly
    fontsize: 1.15em
    linestretch: 1.5
    fontcolor: "#e0e0e0"   
    toc: true
    code-fold: true
    fig-align: center
    grid:
      body-width: 1000px

css: styles.css
