project:
  type: website

website:
  title: "Evolución de la Sequía en México"
  description: "Análisis territorial y temporal (PRONACOSE)"
  navbar:
    left:
      - href: index.qmd
        text: Inicio
      - href: mis_reportes/reporte-01.qmd
        text: Exploración y Limpieza
      - href: mis_reportes/reporte-02.qmd
        text: Análisis y Modelado
      - href: mis_reportes/reporte-03.qmd
        text: Resultados y Conclusiones

format:
  html:
    theme: sandstone
    css: styles.css
    toc: true
    code-fold: true 
    execute:
      warning: false
      message: false