---
title: "Conclusiones"
jupyter: python3
execute:
  cache: true
  warning: false
  message: false
---

::: {.callout-important icon=false}
## Necesitamos cambiar nuestro sesgo!
La sequía en México ha dejado de ser un fenómeno transitorio para convertirse en una crisis crónica. Sin embargo,  no podemos solamente **medir la falta de lluvia** para tomar desición sobre cuales regiones priorizar inversión y recursos. 

- **Es decir, el presupuesto no debe asignarse donde simplemente "falta el agua", sino donde su ausencia detona el mayor daño social y económico.**

:::

## ¿En que estados hay mayor riesgo frente una sequía?

Para traducir el análisis algorítmico en estrategias ejecutivas, el modelo se escaló a una visión macro-regional. El siguiente índice permite visualizar de inmediato qué entidades federativas concentran el mayor riesgo global acumulado.

```{python}
#| code-fold: true
#| code-summary: "Ver código del Mapa de Riesgo Estatal"

import pandas as pd
import plotly.express as px
import requests
from sklearn.impute import SimpleImputer
from sklearn.preprocessing import StandardScaler

df = pd.read_parquet("../data/processed/municipios_clusterizados.parquet")

features = ['frecuencia_sequia_pct', 'racha_maxima_quincenas', 
            'vulnerabilidad_ambiental', 'vulnerabilidad_social', 'vulnerabilidad_economica']

X_scaled = StandardScaler().fit_transform(SimpleImputer(strategy='median').fit_transform(df[features]))
df['Indice_Riesgo_Global'] = X_scaled.sum(axis=1)

riesgo_estatal = df.groupby('ENTIDAD', as_index=False)['Indice_Riesgo_Global'].mean()
riesgo_estatal = riesgo_estatal.sort_values('Indice_Riesgo_Global', ascending=False)

url_geojson = "https://raw.githubusercontent.com/angelnmara/geojson/master/mexicoHigh.json"
mx_regiones = requests.get(url_geojson).json()

mapa_nombres = {
    'Veracruz de Ignacio de la Llave': 'Veracruz', 
    'Michoacán de Ocampo': 'Michoacán', 
    'Coahuila de Zaragoza': 'Coahuila',
    'Estado de México': 'México',
    'Querétaro de Arteaga': 'Querétaro'
}
riesgo_estatal['ENTIDAD_MAPA'] = riesgo_estatal['ENTIDAD'].replace(mapa_nombres)

fig_mapa = px.choropleth(
    riesgo_estatal,
    geojson=mx_regiones,
    featureidkey='properties.name',
    locations='ENTIDAD_MAPA',
    color='Indice_Riesgo_Global',
    color_continuous_scale='Reds',
    title='<b>Índice Promedio de Riesgo Hídrico por Entidad Federativa</b>',
    labels={'Indice_Riesgo_Global': 'Nivel de Riesgo (Z-score)'}
)

fig_mapa.update_geos(fitbounds="locations", visible=False)
fig_mapa.update_layout(margin={"r":0,"t":50,"l":0,"b":0}, template='plotly_white')
fig_mapa.show()
```


## ¿Cúales son los municipios de mayor riesgo a colapsar frente una sequía?

```{python}
#| code-fold: true
#| code-summary: "Ver código de la Matriz de Riesgo"

import pandas as pd
import plotly.express as px

df = pd.read_parquet("../data/processed/municipios_clusterizados.parquet")

df['Vulnerabilidad_Total'] = df['vulnerabilidad_ambiental'] + df['vulnerabilidad_social'] + df['vulnerabilidad_economica']

df_plot = df.dropna(subset=['Vulnerabilidad_Total', 'frecuencia_sequia_pct']).copy()

fig_scatter = px.scatter(
    df_plot,
    x='frecuencia_sequia_pct',
    y='Vulnerabilidad_Total',
    color='Perfil_Riesgo',
    hover_name='NOMBRE_MUN',
    hover_data={'ENTIDAD': True, 'Perfil_Riesgo': False, 'Vulnerabilidad_Total': ':.2f'},
    color_discrete_map={
    'Resilientes': '#47a74b',
    'Prioritarios': '#8d2b2b', 
    'Intervención Crítica': '#070606', 
    },
    title='<b>Matriz de Riesgo: Peligro Histórico vs Fragilidad Estructural</b>',
    labels={
        'frecuencia_sequia_pct': '% de Quincenas en Sequía (Peligro)',
        'Vulnerabilidad_Total': 'Índice de Vulnerabilidad Acumulada'
    },
    opacity=0.7
)

fig_scatter.update_layout(
    template='plotly_white',
    legend_title_text='Segmento',
    legend=dict(orientation="h", y=-0.2),
    margin=dict(l=20, r=20, t=50, b=20)
)

```

Así, veemos que el riego real de un municipio no depende de la frecuencia de lluvía o sequía, sino de qué tan frágil es el municipio que la recibe.


- ⚫ Intervención Crítica (Alta sequía + Alta vulnerabilidad): Representa el peor escenario posible. Requiere ayuda humanitaria inmediata y contención de daños, ya que la exposición histórica máxima coincide con una estructura comunitaria insostenible.

- 🔴 Prioritarios (Baja sequía + Alta vulnerabilidad): Las "bombas de tiempo" territoriales. La inversión aquí debe centrarse en desarrollo de resiliencia y mitigación social (cisternas comunitarias, subsidios preventivos) antes de que la próxima crisis climática los impacte.

- 🟢 Resilientes (Alta/Baja sequía + Baja vulnerabilidad): Municipios cuya robustez socioeconómica amortigua el estrés hídrico. El presupuesto debe dirigirse hacia la infraestructura a largo plazo y modernización tecnológica (presas, tecnificación de riego), y no hacia el asistencialismo de emergencia.



### Conclusiones
El análisis histórico demuestra que la sequía en México ha dejado de ser un fenómeno transitorio. Aunque durante el periodo 2016–2022 predominaron condiciones de menor intensidad, la crisis de 2023 y 2024 marcó un punto de inflexión con una expansión sin precedentes de sequías severas y extremas. Asimismo, el análisis de persistencia revela que múltiples municipios enfrentan el estrés hídrico no como un evento aislado, sino como una condición recurrente y crónica.

La aportación central de esta investigación es demostrar que medir únicamente la falta de lluvia es insuficiente para la toma de decisiones. Al integrar el peligro climático con la vulnerabilidad estructural (ambiental, social y económica) mediante el algoritmo de K-Means, logramos decodificar el ADN del riesgo hídrico nacional en tres perfiles territoriales operativos:

- Como se observa en la Matriz de Riesgo, esta metodología permitió aislar el clúster de **Intervención Crítica** (puntos negros), que representa el peor escenario posible: máxima exposición histórica combinada con una vulnerabilidad estructural insostenible.   
- A su vez, el modelo identificó a los municipios **Prioritarios** (puntos rojos), descubriendo verdaderas "bombas de tiempo". Estos territorios engañan a los promedios tradicionales porque sufren poca sequía (peligro bajo), pero su fragilidad es tan extrema que un solo evento climático atípico tendría consecuencias devastadoras inmediatas.
- Finalmente, el grupo de **Resilientes** (puntos verdes) agrupa a aquellos municipios cuya robustez socioeconómica amortigua el impacto de la sequía, independientemente de su frecuencia.

Para traducir estos hallazgos matemáticos en estrategias ejecutivas, el modelo se escaló a una visión macro-regional. El Índice Promedio de Riesgo Hídrico a nivel estatal permite a los tomadores de decisiones visualizar de inmediato qué entidades federativas concentran el mayor riesgo global acumulado. Esta proyección geográfica facilita la asignación de recursos federales y la planeación de políticas públicas adaptadas a la realidad de cada estado.

Finalmente, estos resultados proporcionan una línea base robusta para abandonar las declaratorias generales de emergencia y transitar hacia políticas "quirúrgicas". El modelo territorial construido en este proyecto demuestra que el presupuesto público no debe asignarse solo donde falta el agua, sino donde su ausencia genera el mayor daño social y económico, permitiendo intervenciones diferenciadas: ayuda humanitaria para la zona de intervención crítica, desarrollo de resiliencia para los municipios prioritarios, e infraestructura a largo plazo para las regiones resilientes.